security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: localhost:9191/oauith/authorize
      access-token-uri: http://localhost:9191/oauth/token
    resource:
      token-info-uri:

server:
  servlet:
    session:
      cookie:
        name: KSESSION
